* <2024-04-16 k>
Ne egy pont 3–5 álláspont.

Be kellene tájékozni. Mérőállomással is mérée.

Egymáshoz tájékozni.

Legalább EOV pontokat.

Kb. téglalap. egy középen. ahol mér. Kb. négyzet.

Milyen legyen a négyzet. Kicsi vagy nagy szkenner. Kicsi.
Nagy a szoftver összeforgatja. Kicsi a tájékozást az ember csinálhatja.
Egy szkennelést elvágunk.

15 M szoftver megcsinál mindent. Ingyenes szoftver cloud compare. Hamar ponthalmaz
és látványos. Fotoállványon magasra fel lehet tenni a kicsit.

Cövekkel megjelölni és utólag megmérni. Tárcsát a cövekekre.

Közös pontok belülre.

Mennyi idő lesz. Pénteken.

Szkennelve cövekekkel az ismert koordinátájú pontok. 2-3 kellene. Azokon tárcsa.
Azon kívül kijelölni a műszerálláspontok és kapcsolópontok.

Tárcsát pontosan lássa max 15 méter a három közeli tárcsához.

60 m a hatótávolsága a kis szkennernek.

Nem baj, ha nem annyira pontos.

Össze kell tájékozni.

EOV először, utána feldolgozás.

Gyenizse-Nagy Balázs

** Eszközök
5 láb
kis szkenner
3 óra

Egyik legalább nyíltabb helyen, illesztő pont.

Jelmagasságokat mérjük!

* <2024-06-27 cs>
A veszprémi TLS pontfelhőket átkonvertáltam BIN formátumra, amit már a
CloudCompare-rel is meg tudunk nyitni.

A tárcsák középpontját a Leica Cyclone programmal automatikusan
felkerestem, és beírtam a BIN formátumú fájlokba. A BIN fájlok tehát
egyrészt a pontfelhőt, másrészt a tárcsák középponti koordinátáját
tartalmazzák. Ezt tekintjük a feldolgozás kiindulási állapotának. A
fájlok a megosztott mappában megtalálhatók. Javaslom, hogy az ott
tárolt állományokat saját gépre töltsd le, és CloudCompare-rel meg is
nézheted őket.

Teendők:
- [ ] Mérési vázlat készítse, ami közelítő jelleggel tartalmazza a TLS
  álláspontokat (azonosítóval), és a kapcsolópontokat
  (azonosítóval). TLS álláspontok azonosítójaként a ponthalmazok
  műszerben létrehozott fájlneveit javaslom, ami 50, 51, 52, 54, 55. A
  számozás a felmérések sorrendjét követi. Az 55-ös a középső álláspont,
  amihez m a másik négyet kapcsoljuk.
- [ ] A vázlat alapján megállapítani, hogy az egyes álláspontokról az
  55-ös felvétel mely kapcsolópontjainak kell(ene) látszódni.
- [ ] A megosztott mappában található kapcsolopontok.xlsx táblázat
  kitöltése, ami a GNSS méréseket tartalmazza. A mezőnevekhez
  megjegyzésbe magyarázatot írtam.

A tájékozást két lépésben végezzük majd el. Először minden ponthalmazt
hozzátájékozzuk az 55-öshöz (relatív tájékozás), majd az egyesített
pontfelhőt a kapcsolópontok GNSS koordinátája alapján átszámítjuk
EOV-be (abszolút tájékozás).

* <2024-06-28 p>
Beszéltünk, hogy 5 hét múlva tudok rajta dolgozni.

Legyen egy térkép, amin látszik, hogy melyik pont melyik?

Az volt a fejében, hogy nem lett jó az RTK. de mégis. Majd küld valamit.

