* <2024-04-16 k>
Ne egy pont 3–5 álláspont.

Be kellene tájékozni. Mérőállomással is mérée.

Egymáshoz tájékozni.

Legalább EOV pontokat.

Kb. téglalap. egy középen. ahol mér. Kb. négyzet.

Milyen legyen a négyzet. Kicsi vagy nagy szkenner. Kicsi.
Nagy a szoftver összeforgatja. Kicsi a tájékozást az ember csinálhatja.
Egy szkennelést elvágunk.

15 M szoftver megcsinál mindent. Ingyenes szoftver cloud compare. Hamar ponthalmaz
és látványos. Fotoállványon magasra fel lehet tenni a kicsit.

Cövekkel megjelölni és utólag megmérni. Tárcsát a cövekekre.

Közös pontok belülre.

Mennyi idő lesz. Pénteken.

Szkennelve cövekekkel az ismert koordinátájú pontok. 2-3 kellene. Azokon tárcsa.
Azon kívül kijelölni a műszerálláspontok és kapcsolópontok.

Tárcsát pontosan lássa max 15 méter a három közeli tárcsához.

60 m a hatótávolsága a kis szkennernek.

Nem baj, ha nem annyira pontos.

Össze kell tájékozni.

EOV először, utána feldolgozás.

Gyenizse-Nagy Balázs

** Eszközök
5 láb
kis szkenner
3 óra

Egyik legalább nyíltabb helyen, illesztő pont.

Jelmagasságokat mérjük!
