#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: Adatcsere formátumok a magyar ingatlan-nyilvántartásban
#+subtitle: Data exchange formats in the Hungarian land registry
#+date: 2024
#+author: Kalicz Péter
#+email: kalicz.peter@uni-sopron.hu
#+language: hu
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:
#+latex_class: article
#+latex_class_options: [12pt,twoside,a4paper]
#+latex_header: \usepackage[margin=1in,bindingoffset=0.2in]{geometry}
#+latex_header: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage[english,AUTO]{babel}
#+latex_header: \usepackage[style=authoryear,autolang=langname,backend=biber,sortlocale=hu]{biblatex}
#+latex_header: \addbibresource{source.bib}
#+latex_header: \DeclareNameAlias{default}{family-given}
#+latex_header: \renewcommand{\revsdnamepunct}{\iffieldequalstr{langid}{magyar}{}{\addcomma\space}}
#+latex_header: \renewcommand{\labelnamepunct}{\addcolon\space}
#+latex_header: \renewcommand{\nameyeardelim}{ }
#+latex_header: \renewcommand{\postnotedelim}{: }
#+latex_header: \DeclareFieldFormat{postnote}{#1}
#+latex_header: \usepackage{pdfpages}
#+latex_header: \usepackage{csquotes}
#+latex_header: \usepackage{titlesec}
#+latex_header: \newcommand{\sectionbreak}{\clearpage}
#+latex_header_extra:
#+description:
#+keywords: gml
#+latex_compiler: pdflatex

\frenchspacing

#+begin_src emacs-lisp :exports results :results none :eval export
    (make-variable-buffer-local 'org-latex-title-command)
    (setq org-latex-title-command (concat
				 "\\newcommand{\\cimem}{ %t }\n"
				 "\\newcommand{\\nevem}{ %a }\n"
       "\\begin{titlepage}\n"
       "Logo \\par \n"
       "Geomatikai és Kultúrmérnöki Intézet \\par \n"
       "\\vspace{100px}\n"
       "\\centering\n"
     "{\\large Szakdolgozat \\par}\n"
     "\\vspace{\\baselineskip}\n"
     "{\\noindent\\parbox{265px}{\\centering\\LARGE %t} \\par }\n"
     "\\vspace{\\baselineskip}\n"
     "{\\large %s \\par} \n"
     "\\vspace{\\fill} \n"
       "{\\normalsize Készítette: %a \\par}\n"
       "\\vspace 3 \n"
       "{\\normalsize %D \\par}\n"
       "\\end{titlepage}\n"))
#+end_src

This page remains intentionally blank.
#+LATEX: \newpage{}


#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Szakdolgozat feladat}
\includepdf[pages=1]{KaliczPéterSzakdolgozatkiírás.pdf}

This page remains intentionally blank.
#+LATEX: \newpage{}


#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Szerzői nyilatkozat}
* Szerzői nyilatkozat
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

\bigskip

Alulírott \nevem (neptun kód: XQ0E04) jelen nyilatkozat
aláírásával kijelentem, hogy az\cimem{} című:

#+BEGIN_CENTER
*szakdolgozat*
#+END_CENTER

\noindent (a továbbiakban: dolgozat) *önálló munkám*, a dolgozat
készítése során betartottam a /szerzői jogról szóló 1999. évi
LXXVI. tv/. szabályait, valamint az Egyetem által előírt, a dolgozat
készítésére vonatkozó szabályokat, különösen a hivatkozások és
idézések tekintetében[fn:1].

Kijelentem továbbá, hogy a dolgozat készítése során az önálló munka
kitétel tekintetében a konzulenst illetve a feladatot kiadó oktatót
\textbf{nem tévesztettem meg}.

Jelen nyilatkozat aláírásával tudomásul veszem, hogy amennyiben
bizonyítható, hogy a dolgozatot *nem magam készítettem*, vagy a
dolgozattal kapcsolatban szerzői jogsértés ténye merül fel, a Soproni
Egyetem *megtagadja a dolgozat befogadását és ellenem fegyelmi
eljárást indíthat*.


A dolgozat befogadásának megtagadása és a fegyelmi eljárás indítása
nem érinti a szerzői jogsértés miatti egyéb (polgári jogi,
szabálysértési jogi, büntetőjogi) jogkövetkezményeket.

Kijelentem, hogy a dolgozatot más szakon – más felsőoktatási
intézményre vonatkozóan is – nem nyújtottam be.

Sopron, \today

#+BEGIN_EXPORT latex
\vspace{3cm}
\begin{flushright}
\parbox{5cm}{\centering\dotfill\newline\nevem}
\end{flushright}
#+END_EXPORT
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Tartalomjegyzék}
#+TOC: headlines 2
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Bevezetés}
* Bevezetés
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

Gyermekkoromban – ha jól emlékszem történelem tantárgyból a honismeret
témakörében – feladat volt egy térkép készítés. A térkép célja az
akkori lakóhelyem, Kunhegyes város belterületének ábrázolása volt. Ma
már – az internetről ingyenesen elérhető és nagyon részletes digitális
térképek korában – elképzelhetetlen, hogy akkor nekem milyen nehéz
volt e feladat. Rájöttem, hogy lakóhelyemnek csak kicsi részét
ismerem, ráadásul nem volt kedvem végijárni az általam nem igazán
ismert utcákat sem, hogy összegyűjtsem neveiket, megismerjem
vonalvezetésüket. Összekavarodtak az utcanevek a rajzon. Azután jöttek
a technikai jellegű problémák. Jó nagyban rajzoltam fel a jól ismert
utcákat, s ahogy bővült a térkép egyre kisebb helymaradt a hosszabb,
nagyobb utcáknak. Emlékeim szerint egészen a lap széléig rajzoltam, de
még azok az utcák sem fértek fel rendesen, amelyekhez elsétáltam, azt
sem tudtam, hogy hol a széle a városkának. Életemnek egy máig fájó
kudarca volt e térkép.

# A térkép pontos neve!!!!!
Látva kudarcomat Édesanyám szerzett egy áttekintő térképet. Ez a
térkép számomra nagyon furcsának tűnt, mert az iskolai atlaszomban
szinte csak színes, szépen kartografált térképek voltak, amelyektől
nagyon elütött ez a térkép. Puritánsága és a jelkulcs hiánya ellenére
a jól imert részeket tanulmányozva hamar rájöttem, hogy hogyan kell
értelmezni e térképet. Ahogy visszaemlékszem később sokat nézegettem,
s máig őrzöm a szépen hajtogatott kopott térképlapot.

Jó pár évvel később családommal vásárolutnk egy külterületi telket,
hogy rajta zöldséget, gyümölcsöt termesszünk. A régi tulajdonos
átadott egy pici gyűrütt térképlapot, ahol a kertben lévő kis
szerszámtároló épület volt ábrázolva, hasonló stílusban és
technikával, mint a fent említett térképen. Ez egy épületfeltüntetési
vázrajz volt, amelyet a korábbi tulajdonosnak kellett csináltatni,
miután egy helyszíni szemle után kiderült, hogy engedély nélkül
építette fel a házikót. A vázrajzot nézegetve eszembe jutott a régi
térképlap.

Magyarországon az ingatlan-nyilvántartási célú munkák nagy változáson
fognak keresztül menni. Bár már nem a fent említett analóg térképeket
cserélik le, hanem a korábban használt rendszer változik meg. Annak a
DAT adatcsere formátumnak mondunk hamarosan búcsút, amely az
ingatlan-nyilvántartási célú földmérési tevékenység végzéséhez vitték
az állami adatokat a földmérőkhöz. Ezek alapján több mint negyed
százada készülnek vázrajzok, jutnak el a felhasználokhoz az
ingatlan-nyilvántartási térképi adatbázisból az adatok.

Dolgozatomban a régi adatcsere formátum bemutatása után számba veszem,
hogy milyen formátumok jöhettek volna szóba helyette? Részletesen
bemutatom az E-ING megvalósítói által kiválasztott gml formátumot, s
végül megkísérlek egy oktatási célokra E-ING gml formátumú fájlokat
generáló rendszert elkészíteni.
#+LATEX: \newpage{}

* Az ingatlan-nyilvántartásban jelenleg használt adatcsere formátum
Ismertesse az ingatlan-nyilvántartásban jelenleg használt adatcsere formátumot!

** Analóg térképtől a digitálisig

** DAT és az adatcsere formátuma
A szabvány \parencite{msz97:_dat} és a hozzá kapcsolódó szabályzat definiálja.

A DAT formátum Magyarországon bevezetése óta alapvető
adatcsere-formátum volt az ingatlan-nyilvántartási adatok kezelésére,
amellyel a földhivatalok eleget tettek adatszolgáltatási kötelezettségüknek.

A DAT formátum alapvetően szöveges fájlformátum volt, és a szabványban
\parencite{msz97:_dat} meghatározott, a DAT szabályzat mellékletében
részletesen megadott táblák egyszerű szöveges adatsorokkák
leképezésével dolgozott. A táblák különböző mezőkbe rendezett
információit csillag mezőelválasztóval elválasztva fordította
szövegfájlba. Az adattáblák tartalmazzák az alapvető
ingatlaninformációkat, például a helyrajzi számot, területnagyságot,
tulajdonosok nevét, és rengeteg egyéb jogi és műszaki adatokat.

A DAT szabályzatban előírt egyszerű szöveges formátum könnyen kezelhetővé tette a fájlokat
bármilyen egyszerű szövegfájlok kezelésére alkalmas szoftverrel.

Ezek alapján elméletben lehetővé tette volna a különböző térbeli
adatokat kezelő programokba történő beolvasást is, hiszen egy nyílt
specifikációról van szó. Azonban a geoinformatikai szoftverekbe
történő beolvasás során a nem egyszerűen megvalósítható
adatkapcsolatok és a különböző típusú adatok közötti összefüggések
leképezése nehézzé tette a megvalósítást. Jelentős adatvesztés, a
tárolt adatok körének csak részben történő leképezésével valósulhatott
meg leképezés.  A fenti problémák, valamint a formátummal dolgozók
szűk köre miatt csak néhány szoftver támogatja teljességében a
formátumot.

# ITR FreeTR mellett megkeresni a beolvasó programot!!!!!

A DAT formátum az 1990-es évek technológiai határai, az előre nem
látható fejlődés miatt nem lehet olyan mértékben interoperábilis, hogy
megfeleljen a modern adatkezelési technológiáknak és mai
adatmegosztási elvárásoknak.
#+LATEX: \newpage{}

* A geoinformatikában elterjedt adatcserére szolgáló fájltípusok
Mutassa be a geoinformatikában elterjedt, ilyen célra felhasználható
fájlformátumokat, térjen ki, hogy melyek lehetnek alkalmasak a
korábbi formátum leváltására!

A rendszer alapja az MSZ7772-1 számú DAT szabvány \parencite{msz97:_dat, mihaly23:terinfo}. Az
adatcsere formátum használatát a szabvány technikai kiegészítésére készült DAT1 szabályzat
hetedik fejezetében \parencite{mihály96:_dat1}, illetve annak első melléklete
\parencite{mihály18:m1} írja le a negyedik fejezetében írja elő. A szabályzat G. mellékletében
találjuk részletes specifikációját.

** OGC gml
Részletes mutassa be az OGC gml szerkezetét, térjen ki arra, hogy
milyen, a magyar ingatlan-nyilvántartás szempontjából fontos
bővítésekkel terveznek bevezetni új adatcsere formátumot!

** E-ing bővítések
A Földhivatali portálon közzétett séma írja le a formátumot
\parencite{földhivatal24:einggml}.

Az e-ing gml azonosító adatait az alábbiakban láthatjuk:
#+ATTR_LATEX: :float t
#+BEGIN_SRC xml
  <gml:metaDataProperty>
    <gml:GenericMetaData>
      <MetaDataList>
	<gmlID>691da01c-7911-45a7-b831-23a17bb7ff35</gmlID>
        <gmlExportDate>1729251153420</gmlExportDate>
        <gmlGeobjIds>4319328552436</gmlGeobjIds>
        <xsdVersion>2.3</xsdVersion>
      </MetaDataList>
    </gml:GenericMetaData>
  </gml:metaDataProperty>
#+END_SRC
#+LATEX: \newpage{}

* A generálásban felhasználható szoftvereszközök
Az adatbázis építéshez némi keresgélés után sem találtam speciális programot.

** R

** sf
A simple feature megvalósítását R-ben az sf csomag valósítja meg
\parencite{pebesma18:sf_rj}.

** XML generálás
Az xml/gml fájlok előállításához az Duncan Temple Lang és Tomas
Kalibera által fejlesztett XML csomagot választottam
\parencite{xmlpackage}. Szóba jöhetett volna az xml2? is, de ott az xml
attribútumok generálása nem működött

Nagyon jó könyv is van \parencite{nolantemplelang2013xml}.
#+LATEX: \newpage{}

* E-ING gml generáló program
Készítsen az E-ING gml formátummal kompatibilis fájlok generálására alkalmas programot!
#+LATEX: \newpage{}

* Összefoglalás
Dolgozatomban bemutattam az intatlan-nyilvántartási célú földmérési
tevékenységekhez használt adatcsere formátum kivezetésre kerülő
változatát.  Áttekintettem azokat az adatcserére használható
formátumokat, amelyek elterjedtek, s akár bevezetésre is kerülhettek
volna a magyar rendszerben. Részletesen bemutattam az OGC gml
szabványán alapuló E-ING számára kifejlesztett fájlformátumot.

Az új formátum megismeréséhez, a formátummal történő munka
gyakorlásához az R program segítségével készítettem egy fájlok
generálására alkalmas rendszert.
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Köszönetnyilvánítás}
* Köszönetnyilvánítás
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
Mindenek előtt köszönöm feleségemnek és gyermekeimnek a képzés és e
dolgozat megírása során tanúsított türelmüket és
támogatásukat. Köszönöm Édesanyámnak a térképet, amelyet nekem
szerzett. Kollégámnak Gribovszki Zoltánnak, aki igyekezett a rám
zúduló feladatoktól mentesíteni – néha úgy éreztem erejét meghaladóan
is –, hogy tudjak haladni doglozatommal.
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Irodalomjegyzék}
* Irodalomjegyzék
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
#+LATEX: \printbibliography[heading=none]


* Footnotes

[fn:1] *1999. évi LXXVI. tv. 34. §* (1) A mű részletét – az
átvevő mű jellege és célja által indokolt terjedelemben és az
eredetihez híven – a forrás, valamint az ott megjelölt szerző
megnevezésével bárki idézheti.\par *36. §* (1) Nyilvánosan
tartott előadások és más hasonló művek részletei, valamint politikai
beszédek tájékoztatás céljára – a cél által indokolt terjedelemben –
szabadon felhasználhatók. Ilyen felhasználás esetén a forrást – a
szerző nevével együtt – fel kell tüntetni, hacsak ez lehetetlennek nem
bizonyul.

