#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: Adatcsere formátumok a magyar ingatlan-nyilvántartásban
#+subtitle: Data exchange formats in the Hungarian land registry
#+date: 2024
#+author: Kalicz Péter
#+email: kalicz.peter@uni-sopron.hu
#+language: hu
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:
#+latex_class: article
#+latex_class_options: [12pt,a4paper]
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage{indentfirst}
#+latex_header: \usepackage[hungarian]{babel}
#+latex_header: \usepackage[autolang=other,backend=biber,sortlocale=hu]{biblatex}
#+latex_header: \addbibresource{source.bib}
#+latex_header: \DeclareNameAlias{default}{family-given}
#+latex_header: \renewcommand*{\revsdnamepunct}{}
#+latex_header: \renewcommand{\labelnamepunct}{\addcolon\space}
#+latex_header: \renewcommand{\nameyeardelim}{ }
#+latex_header: \renewcommand{\postnotedelim}{: }
#+latex_header: \DeclareFieldFormat{postnote}{#1}
#+latex_header: \usepackage{pdfpages}
#+latex_header_extra:
#+description:
#+keywords: gml
#+latex_compiler: pdflatex

\frenchspacing

#+begin_src emacs-lisp :exports results :results none :eval export
    (make-variable-buffer-local 'org-latex-title-command)
    (setq org-latex-title-command (concat
       "\\begin{titlepage}\n"
       "Logo \\par \n"
       "Geomatikai és Kultúrmérnöki Intézet \\par \n"
       "\\vspace{100px}\n"
       "\\centering\n"
     "{\\large Szakdolgozat \\par}\n"
     "\\vspace{\\baselineskip}\n"
     "{\\noindent\\parbox{265px}{\\centering\\LARGE %t} \\par }\n"
     "\\vspace{\\baselineskip}\n"
     "{\\large %s \\par} \n"
     "\\vspace{\\fill} \n"
       "{\\normalsize Készítette: %a \\par}\n"
       "\\vspace 3 \n"
       "{\\normalsize %D \\par}\n"
       "\\end{titlepage}\n"))
#+end_src

\includepdf[pages=1]{KaliczPéterSzakdolgozatkiírás.pdf}

Szerzőijogi nyilatkozat
\newpage{}

#+TOC: headlines 2

* Bevezetés

* Az ingatlan-nyilvántartásban jelenleg használt adatcsere formátum
Ismertesse az ingatlan-nyilvántartásban jelenleg használt adatcsere formátumot!

* A geoinformatikában elterjedt adatcserére szolgáló fájltípusok
Mutassa be a geoinformatikában elterjedt, ilyen célra felhasználható
fájlformátumokat, térjen ki, hogy melyek lehetnek alkalmasak a
korábbi formátum leváltására!

** OGC gml
Részletes mutassa be az OGC gml szerkezetét, térjen ki arra, hogy
milyen, a magyar ingatlan-nyilvántartás szempontjából fontos
bővítésekkel terveznek bevezetni új adatcsere formátumot!

** E-ing bővítések

* A generálásban felhasználható szoftvereszközök
Az adatbázis építéshez némi keresgélés után sem találtam speciális programot.

** R

** sf

** XML generálás
Az xml/gml fájlok előállításához az Duncan Temple Lang és Tomas
Kalibera által fejlesztett XML csomagot választottam
\cite{xmlpackage}. Szóba jöhetett volna az xml2? is, de ott az xml
attribútumok generálása nem működött

Nagyon jó könyv is van \cite{nolantemplelang2013xml}.

* E-ING gml generáló program
Készítsen az E-ING gml formátummal kompatibilis fájlok generálására alkalmas programot!

* Összefoglalás

\newpage{}
* Irodalomjegyzék
\printbibliography[heading=none]
