#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: Adatcsere formátumok a magyar ingatlan-nyilvántartásban
#+subtitle: Data exchange formats in the Hungarian land registry
#+date: 2024
#+author: Kalicz Péter
#+email: kalicz.peter@uni-sopron.hu
#+language: hu
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:
#+latex_class: article
#+latex_class_options: [12pt,twoside,a4paper]
#+latex_header: \usepackage[margin=1in,bindingoffset=0.2in]{geometry}
#+latex_header: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage[english,AUTO]{babel}
#+latex_header: \usepackage[style=authoryear,autolang=langname,backend=biber,sortlocale=hu]{biblatex}
#+latex_header: \addbibresource{source.bib}
#+latex_header: \DeclareNameAlias{sortname}{family-given}
#+latex_header: \renewcommand{\revsdnamepunct}{\iffieldequalstr{langid}{magyar}{}{\addcomma\space}}
#+latex_header: \renewcommand{\labelnamepunct}{\addcolon\space}
#+latex_header: \renewcommand{\nameyeardelim}{ }
#+latex_header: \renewcommand{\postnotedelim}{: }
#+latex_header: \DeclareFieldFormat{postnote}{#1}
#+latex_header: \usepackage{pdfpages}
#+latex_header: \usepackage{csquotes}
#+latex_header: \usepackage{titlesec}
#+latex_header: \usepackage{shapepar}
#+latex_header: \newcommand{\sectionbreak}{\clearpage}
#+latex_header_extra: \newcommand\titleshape{ {0}
#+latex_header_extra: {0} b{0}\\
#+latex_header_extra: {0} t{-2.7}{5.4}\\
#+latex_header_extra: {2} t{-5.5}{11}\\
#+latex_header_extra: {2} e{5} }
#+description:
#+keywords: gml
#+latex_compiler: pdflatex

\frenchspacing

#+begin_src emacs-lisp :exports results :results none :eval export
    (make-variable-buffer-local 'org-latex-title-command)
    (setq org-latex-title-command (concat
				 "\\newcommand{\\cimem}{ %t }\n"
				 "\\newcommand{\\nevem}{ %a }\n"
       "\\begin{titlepage}\n"
       "Logo \\par \n"
       "Geomatikai és Kultúrmérnöki Intézet \\par \n"
       "\\vspace{100px}\n"
       "\\centering\n"
     "{\\large Szakdolgozat \\par}\n"
     "\\vspace{\\baselineskip}\n"
     "{\\LARGE \\shapepar{\\titleshape}%t \\par }\n"
     "\\vspace{\\baselineskip}\n"
     "{\\large %s \\par} \n"
     "\\vspace{\\fill} \n"
       "{\\normalsize Készítette: %a \\par}\n"
       "\\vspace 3 \n"
       "{\\normalsize %D \\par}\n"
       "\\end{titlepage}\n"))
#+end_src

This page remains intentionally blank.
#+LATEX: \newpage{}


#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Szakdolgozat feladat}
\includepdf[pages=1]{KaliczPéterSzakdolgozatkiírás.pdf}

This page remains intentionally blank.
#+LATEX: \newpage{}


#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Szerzői nyilatkozat}
* Szerzői nyilatkozat
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

\bigskip

Alulírott \nevem (neptun kód: XQ0E04) jelen nyilatkozat
aláírásával kijelentem, hogy az\cimem{} című:

#+BEGIN_CENTER
*szakdolgozat*
#+END_CENTER

\noindent (a továbbiakban: dolgozat) *önálló munkám*, a dolgozat
készítése során betartottam a /szerzői jogról szóló 1999. évi
LXXVI. tv/. szabályait, valamint az Egyetem által előírt, a dolgozat
készítésére vonatkozó szabályokat, különösen a hivatkozások és
idézések tekintetében[fn:1].

Kijelentem továbbá, hogy a dolgozat készítése során az önálló munka
kitétel tekintetében a konzulenst illetve a feladatot kiadó oktatót
\textbf{nem tévesztettem meg}.

Jelen nyilatkozat aláírásával tudomásul veszem, hogy amennyiben
bizonyítható, hogy a dolgozatot *nem magam készítettem*, vagy a
dolgozattal kapcsolatban szerzői jogsértés ténye merül fel, a Soproni
Egyetem *megtagadja a dolgozat befogadását és ellenem fegyelmi
eljárást indíthat*.


A dolgozat befogadásának megtagadása és a fegyelmi eljárás indítása
nem érinti a szerzői jogsértés miatti egyéb (polgári jogi,
szabálysértési jogi, büntetőjogi) jogkövetkezményeket.

Kijelentem, hogy a dolgozatot más szakon – más felsőoktatási
intézményre vonatkozóan is – nem nyújtottam be.

Sopron, \today

#+BEGIN_EXPORT latex
\vspace{3cm}
\begin{flushright}
\parbox{5cm}{\centering\dotfill\newline\nevem}
\end{flushright}
#+END_EXPORT
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Tartalomjegyzék}
#+TOC: headlines 2
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Bevezetés}
* Bevezetés
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

Gyermekkoromban – ha jól emlékszem történelem tantárgyból a honismeret
témakörében – feladat volt egy térkép készítés. A térkép célja az
akkori lakóhelyem, Kunhegyes város belterületének ábrázolása volt. Ma
már – az internetről ingyenesen elérhető és nagyon részletes digitális
térképek korában – elképzelhetetlen, hogy akkor nekem milyen nehéz
volt e feladat. Rájöttem, hogy lakóhelyemnek csak kicsi részét
ismerem, ráadásul nem volt kedvem végijárni az általam nem igazán
ismert utcákat sem, hogy összegyűjtsem neveiket, megismerjem
vonalvezetésüket. Összekavarodtak az utcanevek a rajzon. Azután jöttek
a technikai jellegű problémák. Jó nagyban rajzoltam fel a jól ismert
utcákat, s ahogy bővült a térkép egyre kisebb helymaradt a hosszabb,
nagyobb utcáknak. Emlékeim szerint egészen a lap széléig rajzoltam, de
még azok az utcák sem fértek fel rendesen, amelyekhez elsétáltam, azt
sem tudtam, hogy hol a széle a városkának. Életemnek egy máig fájó
kudarca volt e térkép.

# A térkép pontos neve!!!!!
Látva kudarcomat Édesanyám szerzett egy áttekintő térképet. Ez a
térkép számomra nagyon furcsának tűnt, mert az iskolai atlaszomban
szinte csak színes, szépen kartografált térképek voltak, amelyektől
nagyon elütött ez a térkép. Puritánsága és a jelkulcs hiánya ellenére
a jól imert részeket tanulmányozva hamar rájöttem, hogy hogyan kell
értelmezni e térképet. Ahogy visszaemlékszem később sokat nézegettem,
s máig őrzöm a szépen hajtogatott kopott térképlapot.

Jó pár évvel később családommal vásárolutnk egy külterületi telket,
hogy rajta zöldséget, gyümölcsöt termesszünk. A régi tulajdonos
átadott egy pici gyűrütt térképlapot, ahol a kertben lévő kis
szerszámtároló épület volt ábrázolva, hasonló stílusban és
technikával, mint a fent említett térképen. Ez egy épületfeltüntetési
vázrajz volt, amelyet a korábbi tulajdonosnak kellett csináltatni,
miután egy helyszíni szemle után kiderült, hogy engedély nélkül
építette fel a házikót. A vázrajzot nézegetve eszembe jutott a régi
térképlap.

Magyarországon az ingatlan-nyilvántartási célú munkák nagy változáson
fognak keresztül menni. Bár már nem a fent említett analóg térképeket
cserélik le, hanem a korábban használt rendszer változik meg. Annak a
DAT adatcsere formátumnak mondunk hamarosan búcsút, amely az
ingatlan-nyilvántartási célú földmérési tevékenység végzéséhez vitték
az állami adatokat a földmérőkhöz. Ezek alapján több mint negyed
százada készülnek vázrajzok, jutnak el a felhasználokhoz az
ingatlan-nyilvántartási térképi adatbázisból az adatok.

Dolgozatomban a régi adatcsere formátum bemutatása után számba veszem,
hogy milyen formátumok jöhettek volna szóba helyette? Részletesen
bemutatom az E-ING megvalósítói által kiválasztott gml formátumot, s
végül megkísérlek egy oktatási célokra E-ING gml formátumú fájlokat
generáló rendszert elkészíteni.
#+LATEX: \newpage{}

* Az ingatlan-nyilvántartásban jelenleg használt adatcsere formátum
Ismertesse az ingatlan-nyilvántartásban jelenleg használt adatcsere formátumot!

** Analóg térképtől a digitálisig

** DAT és az adatcsere formátuma
A szabvány \parencite{msz97:_dat} és a hozzá kapcsolódó szabályzat definiálja.

A DAT formátum Magyarországon bevezetése óta alapvető
adatcsere-formátum volt az ingatlan-nyilvántartási adatok kezelésére,
amellyel a földhivatalok eleget tettek adatszolgáltatási kötelezettségüknek.

A DAT formátum alapvetően szöveges fájlformátum volt, és a szabványban
\parencite{msz97:_dat} meghatározott, a DAT szabályzat mellékletében
részletesen megadott táblák egyszerű szöveges adatsorokkák
leképezésével dolgozott. A táblák különböző mezőkbe rendezett
információit csillag mezőelválasztóval elválasztva fordította
szövegfájlba. Az adattáblák tartalmazzák az alapvető
ingatlaninformációkat, például a helyrajzi számot, területnagyságot,
tulajdonosok nevét, és rengeteg egyéb jogi és műszaki adatokat.

A DAT szabályzatban előírt egyszerű szöveges formátum könnyen kezelhetővé tette a fájlokat
bármilyen egyszerű szövegfájlok kezelésére alkalmas szoftverrel.

Ezek alapján elméletben lehetővé tette volna a különböző térbeli
adatokat kezelő programokba történő beolvasást is, hiszen egy nyílt
specifikációról van szó. Azonban a geoinformatikai szoftverekbe
történő beolvasás során a nem egyszerűen megvalósítható
adatkapcsolatok és a különböző típusú adatok közötti összefüggések
leképezése nehézzé tette a megvalósítást. Jelentős adatvesztés, a
tárolt adatok körének csak részben történő leképezésével valósulhatott
meg leképezés.  A fenti problémák, valamint a formátummal dolgozók
szűk köre miatt csak néhány szoftver támogatja teljességében a
formátumot.

# ITR FreeTR mellett megkeresni a beolvasó programot!!!!!

A DAT formátum az 1990-es évek technológiai határai, az előre nem
látható fejlődés miatt nem lehet olyan mértékben interoperábilis, hogy
megfeleljen a modern adatkezelési technológiáknak és mai
adatmegosztási elvárásoknak.
#+LATEX: \newpage{}

* A geoinformatikában elterjedt adatcserére szolgáló fájltípusok
Mutassa be a geoinformatikában elterjedt, ilyen célra felhasználható
fájlformátumokat, térjen ki, hogy melyek lehetnek alkalmasak a
korábbi formátum leváltására!

A rendszer alapja az MSZ7772-1 számú DAT szabvány \parencite{msz97:_dat, mihaly23:terinfo}. Az
adatcsere formátum használatát a szabvány technikai kiegészítésére készült DAT1 szabályzat
hetedik fejezetében \parencite{mihály96:_dat1}, illetve annak első melléklete
\parencite{mihály18:m1} írja le a negyedik fejezetében írja elő. A szabályzat G. mellékletében
találjuk részletes specifikációját.

** OGC gml
Részletes mutassa be az OGC gml szerkezetét, térjen ki arra, hogy
milyen, a magyar ingatlan-nyilvántartás szempontjából fontos
bővítésekkel terveznek bevezetni új adatcsere formátumot!

** E-ing bővítések
A Földhivatali portálon közzétett séma írja le a formátumot
\parencite{földhivatal24:einggml}.

Az e-ing gml azonosító adatait az alábbiakban láthatjuk:
#+ATTR_LATEX: :float t
#+BEGIN_SRC xml
  <gml:metaDataProperty>
    <gml:GenericMetaData>
      <MetaDataList>
	<gmlID>691da01c-7911-45a7-b831-23a17bb7ff35</gmlID>
        <gmlExportDate>1729251153420</gmlExportDate>
        <gmlGeobjIds>4319328552436</gmlGeobjIds>
        <xsdVersion>2.3</xsdVersion>
      </MetaDataList>
    </gml:GenericMetaData>
  </gml:metaDataProperty>
#+END_SRC
#+LATEX: \newpage{}

* A generálásban felhasználható szoftvereszközök
Az adatbázis építéshez némi keresgélés után sem találtam speciális programot.

** R

** sf
A simple feature megvalósítását R-ben az sf csomag valósítja meg
\parencite{pebesma18:sf_rj}.

** XML generálás
Az xml/gml fájlok előállításához az Duncan Temple Lang és Tomas
Kalibera által fejlesztett XML csomagot választottam
\parencite{xmlpackage}. Szóba jöhetett volna az xml2? is, de ott az xml
attribútumok generálása nem működött

Nagyon jó könyv is van \parencite{nolantemplelang2013xml}.
#+LATEX: \newpage{}

* E-ING gml generáló program
Készítsen az E-ING gml formátummal kompatibilis fájlok generálására alkalmas programot!
#+LATEX: \newpage{}

* Összefoglalás
Dolgozatomban bemutattam az intatlan-nyilvántartási célú földmérési
tevékenységekhez használt adatcsere formátum kivezetésre kerülő
változatát.  Áttekintettem azokat az adatcserére használható
formátumokat, amelyek elterjedtek, s akár bevezetésre is kerülhettek
volna a magyar rendszerben. Részletesen bemutattam az OGC gml
szabványán alapuló E-ING számára kifejlesztett fájlformátumot.

Az új formátum megismeréséhez, a formátummal történő munka
gyakorlásához az R program segítségével készítettem egy fájlok
generálására alkalmas rendszert.
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Köszönetnyilvánítás}
* Köszönetnyilvánítás
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
Mindenek előtt köszönöm feleségemnek és gyermekeimnek a képzés és e
dolgozat megírása során tanúsított türelmüket és
támogatásukat. Köszönöm Édesanyámnak a térképet, amelyet nekem
szerzett. Kollégámnak Gribovszki Zoltánnak, aki igyekezett a rám
zúduló feladatoktól mentesíteni – néha úgy éreztem erejét meghaladóan
is –, hogy tudjak haladni szakdolgozatom készítésével.
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Irodalomjegyzék}
* Irodalomjegyzék
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
#+LATEX: \printbibliography[heading=none]


* Footnotes

[fn:1] *1999. évi LXXVI. tv. 34. §* (1) A mű részletét – az
átvevő mű jellege és célja által indokolt terjedelemben és az
eredetihez híven – a forrás, valamint az ott megjelölt szerző
megnevezésével bárki idézheti.\par *36. §* (1) Nyilvánosan
tartott előadások és más hasonló művek részletei, valamint politikai
beszédek tájékoztatás céljára – a cél által indokolt terjedelemben –
szabadon felhasználhatók. Ilyen felhasználás esetén a forrást – a
szerző nevével együtt – fel kell tüntetni, hacsak ez lehetetlennek nem
bizonyul.

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{section}{Mellékletek}
* Mellékletek
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{subsection}{Egyszerű gml fájl}
** Egy belterületi földrészletet tartalmazó gml fájl
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

# literate={ö}{{\"o}}1 {á}{{\'a}}1 {é}{{\'e}}1 {í}{{\'i}}1}
#+LATEX: \small
#+ATTR_LATEX: :options numbers=left, literate={ö}{{\"o}}1 {á}{{\'a}}1 {é}{{\'e}}1 {í}{{\'i}}1
#+begin_src XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gml:FeatureCollection xmlns:eing="eing.foldhivatal.hu"
                       xmlns:gml="http://www.opengis.net/gml"
                       xmlns:xlink="http://www.w3.org/1999/xlink"
                       xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--  ===========================================================  -->
  <gml:metaDataProperty>
    <gml:GenericMetaData>
      <MetaDataList>
        <gmlID>691da01c-7911-45a7-b831-bc594bfaca16</gmlID>
        <gmlExportDate>1730355858704</gmlExportDate>
        <gmlGeobjIds>143644558870981</gmlGeobjIds>
        <xsdVersion>2.3</xsdVersion>
      </MetaDataList>
    </gml:GenericMetaData>
  </gml:metaDataProperty>
<!--  ===========================================================  -->
  <gml:featureMembers>
    <eing:FOLDRESZLETEK gml:id="fid-143644558870981">
      <gml:boundedBy>
        <gml:Envelope srsDimension="2"
                      srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:lowerCorner>165800.00 349994.25</gml:lowerCorner>
          <gml:upperCorner>165844.47 350073.91</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <eing:GEOBJ_ID>143644558870981</eing:GEOBJ_ID>
      <eing:OBJ_FELS>BD01</eing:OBJ_FELS>
      <eing:RETEG_ID>20</eing:RETEG_ID>
      <eing:RETEG_NEV>Földrészletek</eing:RETEG_NEV>
      <eing:TELEPULES_ID>3400</eing:TELEPULES_ID>
      <eing:FEKVES>3719</eing:FEKVES>
      <eing:HRSZ>110</eing:HRSZ>
      <eing:FELIRAT>110</eing:FELIRAT>
      <eing:SZINT>0</eing:SZINT>
      <eing:IRANY>0</eing:IRANY>
      <eing:MUVEL_AG>4557</eing:MUVEL_AG>
      <eing:JOGI_TERULET>1147</eing:JOGI_TERULET>
      <eing:geometry>
        <gml:Polygon srsDimension="2"
                     srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:exterior>
            <gml:LinearRing srsDimension="2">
              <gml:posList>165800 350000 165813.85 349994.25
                           165844.47 350068.17 165830.61 350073.91
                           165800 350000
	      </gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>
      </eing:geometry>
    </eing:FOLDRESZLETEK>
<!--  ===========================================================  -->
    <eing:CIMKOORDINATA gml:id="fid-143644558876848">
      <gml:boundedBy>
        <gml:Envelope srsDimension="2"
                      srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:lowerCorner>165822 350034</gml:lowerCorner>
          <gml:upperCorner>165822 350034</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <eing:GEOBJ_ID>143644558876848</eing:GEOBJ_ID>
      <eing:OBJ_FELS>AD01</eing:OBJ_FELS>
      <eing:RETEG_ID>52</eing:RETEG_ID>
      <eing:RETEG_NEV>Címkoordináták</eing:RETEG_NEV>
      <eing:TELEPULES_ID>3400</eing:TELEPULES_ID>
      <eing:HRSZ>110</eing:HRSZ>
      <eing:FELIRAT>1</eing:FELIRAT>
      <eing:SZINT>0</eing:SZINT>
      <eing:IRANY>0</eing:IRANY>
      <eing:PONTSZAM>1</eing:PONTSZAM>
      <eing:PONTKOD>5411</eing:PONTKOD>
      <eing:JELKULCS>36</eing:JELKULCS>
      <eing:FRSZ_ID>143644558870981</eing:FRSZ_ID>
      <eing:geometry>
        <gml:Point srsDimension="2"
                   srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:pos>165822 350034
	  </gml:pos>
        </gml:Point>
      </eing:geometry>
    </eing:CIMKOORDINATA>
<!--  ============== Részletpontok   ============================  -->
    <eing:RESZLETPONTOK gml:id="fid-143644558870983">
      <gml:boundedBy>
        <gml:Envelope srsDimension="2"
                      srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:lowerCorner>165800 350000</gml:lowerCorner>
          <gml:upperCorner>165800 350000</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <eing:GEOBJ_ID>143644558870983</eing:GEOBJ_ID>
      <eing:OBJ_FELS>AC02</eing:OBJ_FELS>
      <eing:RETEG_ID>6</eing:RETEG_ID>
      <eing:RETEG_NEV>Részletpontok</eing:RETEG_NEV>
      <eing:TELEPULES_ID>3400</eing:TELEPULES_ID>
      <eing:HRSZ/>
      <eing:FELIRAT>52421</eing:FELIRAT>
      <eing:SZINT>0</eing:SZINT>
      <eing:IRANY>0</eing:IRANY>
      <eing:MAGASSAG>0</eing:MAGASSAG>
      <eing:PONTSZAM>52421</eing:PONTSZAM>
      <eing:PONTKOD>4236</eing:PONTKOD>
      <eing:JELKULCS>0</eing:JELKULCS>
      <eing:geometry>
        <gml:Point srsDimension="2"
                   srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:pos>165800 350000</gml:pos>
        </gml:Point>
      </eing:geometry>
    </eing:RESZLETPONTOK>
    <eing:RESZLETPONTOK gml:id="fid-143644558870982">
      <gml:boundedBy>
        <gml:Envelope srsDimension="2"
                      srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:lowerCorner>165813.85 349994.25</gml:lowerCorner>
          <gml:upperCorner>165813.85 349994.25</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <eing:GEOBJ_ID>143644558870982</eing:GEOBJ_ID>
      <eing:OBJ_FELS>AC02</eing:OBJ_FELS>
      <eing:RETEG_ID>6</eing:RETEG_ID>
      <eing:RETEG_NEV>Részletpontok</eing:RETEG_NEV>
      <eing:TELEPULES_ID>3400</eing:TELEPULES_ID>
      <eing:HRSZ/>
      <eing:FELIRAT>52426</eing:FELIRAT>
      <eing:SZINT>0</eing:SZINT>
      <eing:IRANY>0</eing:IRANY>
      <eing:MAGASSAG>0</eing:MAGASSAG>
      <eing:PONTSZAM>52426</eing:PONTSZAM>
      <eing:PONTKOD>4236</eing:PONTKOD>
      <eing:JELKULCS>0</eing:JELKULCS>
      <eing:geometry>
        <gml:Point srsDimension="2"
                   srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:pos>165813.85 349994.25
	  </gml:pos>
        </gml:Point>
      </eing:geometry>
    </eing:RESZLETPONTOK>
    <eing:RESZLETPONTOK gml:id="fid-143644558870983">
      <gml:boundedBy>
        <gml:Envelope srsDimension="2"
                      srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:lowerCorner>165844.47 350068.17</gml:lowerCorner>
          <gml:upperCorner>165844.47 350068.17</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <eing:GEOBJ_ID>143644558870983</eing:GEOBJ_ID>
      <eing:OBJ_FELS>AC02</eing:OBJ_FELS>
      <eing:RETEG_ID>6</eing:RETEG_ID>
      <eing:RETEG_NEV>Részletpontok</eing:RETEG_NEV>
      <eing:TELEPULES_ID>3400</eing:TELEPULES_ID>
      <eing:HRSZ/>
      <eing:FELIRAT>52429</eing:FELIRAT>
      <eing:SZINT>0</eing:SZINT>
      <eing:IRANY>0</eing:IRANY>
      <eing:MAGASSAG>0</eing:MAGASSAG>
      <eing:PONTSZAM>52429</eing:PONTSZAM>
      <eing:PONTKOD>4236</eing:PONTKOD>
      <eing:JELKULCS>0</eing:JELKULCS>
      <eing:geometry>
        <gml:Point srsDimension="2"
                   srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:pos>165844.47 350068.17</gml:pos>
        </gml:Point>
      </eing:geometry>
    </eing:RESZLETPONTOK>
    <eing:RESZLETPONTOK gml:id="fid-143644558870983">
      <gml:boundedBy>
        <gml:Envelope srsDimension="2"
                      srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:lowerCorner>165830.61 350073.91</gml:lowerCorner>
          <gml:upperCorner>165830.61 350073.91</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <eing:GEOBJ_ID>143644558870983</eing:GEOBJ_ID>
      <eing:OBJ_FELS>AC02</eing:OBJ_FELS>
      <eing:RETEG_ID>6</eing:RETEG_ID>
      <eing:RETEG_NEV>Részletpontok</eing:RETEG_NEV>
      <eing:TELEPULES_ID>3400</eing:TELEPULES_ID>
      <eing:HRSZ/>
      <eing:FELIRAT>52432</eing:FELIRAT>
      <eing:SZINT>0</eing:SZINT>
      <eing:IRANY>0</eing:IRANY>
      <eing:MAGASSAG>0</eing:MAGASSAG>
      <eing:PONTSZAM>52432</eing:PONTSZAM>
      <eing:PONTKOD>4236</eing:PONTKOD>
      <eing:JELKULCS>0</eing:JELKULCS>
      <eing:geometry>
        <gml:Point srsDimension="2"
                   srsName="urn:x-ogc:def:crs:EPSG:23700">
          <gml:pos>165830.61 350073.91</gml:pos>
        </gml:Point>
      </eing:geometry>
    </eing:RESZLETPONTOK>
  </gml:featureMembers>
</gml:FeatureCollection>
#+end_src
#+LATEX: \normalsize
#+LATEX: \newpage{}

#+LATEX: \phantomsection
#+LATEX: \addcontentsline{toc}{subsection}{Egyszerű gml fájl}
** Egyszerű gml fájlt generáló kód
  :PROPERTIES:
  :UNNUMBERED: t
  :END:

#+LATEX: \small
#+ATTR_LATEX: :options numbers=left, literate={ö}{{\"o}}1 {á}{{\'a}}1 {é}{{\'e}}1 {í}{{\'i}}1
#+begin_src R
  BuildNew <- function(coords, file = "gmlwithmeta.gml",
		       currfid = round(abs(rnorm(1))*10^14),
		       hrsz = 110, adminarea = 1147) {
      require(XML)
      srsName <- "urn:x-ogc:def:crs:EPSG:23700"
      ## Coordinates prepcocessing
      coords.matrix <- matrix(coords, ncol = 2, byrow = TRUE)
      ## Remove duplicated points
      coords.matrix <- coords.matrix[!duplicated(coords.matrix),]
      ## Meta data creation
      newgml <- xmlTree("gml:FeatureCollection",
			namespaces=list(eing="eing.foldhivatal.hu",
					gml="http://www.opengis.net/gml",
					xlink="http://www.w3.org/1999/xlink",
					xs="http://www.w3.org/2001/XMLSchema")
			)
      newgml$setNamespace("gml")
      newgml$addNode("metaDataProperty", close = FALSE)
      newgml$addNode("GenericMetaData", close = FALSE)
      newgml$setNamespace(NULL)
      newgml$addNode("MetaDataList", close = FALSE)
      newgml$addNode("gmlID", "691da01c-7911-45a7-b831-bc594bfaca16")
      newgml$addNode("gmlExportDate", round(as.numeric(Sys.time())*1000))
      newgml$addNode("gmlGeobjIds", currfid)
      newgml$addNode("xsdVersion", 2.3)
      newgml$closeNode()
      newgml$closeNode()
      ## Create gml
      gmlwithmeta <- xmlTreeParse(saveXML(newgml), useInternalNodes = T)
      root <- xmlRoot(gmlwithmeta)
      metadataNode <- newXMLNode("featureMembers", parent = root,
				 namespace = "gml")
      ## Create a parcel node
      parcelNode = newXMLNode("FOLDRESZLETEK", parent=metadataNode,
			      namespace = "eing")
      addAttributes(parcelNode, "gml:id" = paste0("fid-", currfid))
      parcelBounded <- newXMLNode("boundedBy", parent=parcelNode,
				  namespace = "gml")
      parcelEnvelope <- newXMLNode("Envelope", parent=parcelBounded,
				   namespace = "gml")
      addAttributes(parcelEnvelope, srsDimension = 2, srsName = srsName) 
      addChildren(parcelEnvelope,
		  newXMLNode("lowerCorner",
			     paste(min(coords.matrix[,1]),
				   min(coords.matrix[,2])),
			     namespace = "gml"))
      addChildren(parcelEnvelope,
		  newXMLNode("upperCorner",
			     paste(max(coords.matrix[,1]),
				   max(coords.matrix[,2])),
			     namespace = "gml"))
      addChildren(parcelNode, newXMLNode("GEOBJ_ID", currfid,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("OBJ_FELS", "BD01",
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("RETEG_ID", 20,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("RETEG_NEV", "Földrészletek",
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("TELEPULES_ID", 3400,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("FEKVES", 3719,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("HRSZ", hrsz,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("FELIRAT", 110,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("SZINT", 0,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("IRANY", 0,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("MUVEL_AG", 4557,
					 namespace = "eing"))
      addChildren(parcelNode, newXMLNode("JOGI_TERULET", adminarea,
					 namespace = "eing"))
      parcelGeometry <- newXMLNode("geometry", parent=parcelNode,
				   namespace = "eing")
      parcelPolygon <- newXMLNode("Polygon", parent=parcelGeometry,
				  namespace = "gml")
      addAttributes(parcelPolygon, srsDimension = 2, srsName = srsName) 
      parcelExterior <- newXMLNode("exterior", parent=parcelPolygon,
				   namespace = "gml")
      parcelRing <- newXMLNode("LinearRing", parent=parcelExterior,
			       namespace = "gml")
      addAttributes(parcelRing, srsDimension = 2)
      addChildren(parcelRing,
		  newXMLNode("posList", paste(coords, collapse = " "),
			     namespace = "gml"))
      ### Points
      ## Random point geneeration related to original
      currfidother <- currfid + round(abs(rnorm(1))*10^4)
      ## Address coordinate
      addresscoordpoint <- round(colMeans(coords.matrix))
      pointNode <- newXMLNode("CIMKOORDINATA", parent=metadataNode,
			      namespace = "eing")
      addAttributes(pointNode, "gml:id" = paste0("fid-", currfidother))
      pointBounded <- newXMLNode("boundedBy", parent=pointNode,
				 namespace = "gml")
      pointEnvelope <- newXMLNode("Envelope", parent=pointBounded,
				  namespace = "gml")
      addAttributes(pointEnvelope, srsDimension = 2, srsName = srsName)
      addChildren(pointEnvelope,
		  newXMLNode("lowerCorner",
			     paste(addresscoordpoint, collapse = " "),
			     namespace = "gml"))
      addChildren(pointEnvelope,
		  newXMLNode("upperCorner",
			     paste(addresscoordpoint, collapse = " "),
			     namespace = "gml"))
      addChildren(pointNode, newXMLNode("GEOBJ_ID", currfidother,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("OBJ_FELS", "AD01",
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("RETEG_ID", 52,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("RETEG_NEV", "Címkoordináták" ,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("TELEPULES_ID", 3400,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("HRSZ", hrsz,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("FELIRAT", 1,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("SZINT", 0,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("IRANY", 0,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("PONTSZAM", 1,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("PONTKOD", 5411,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("JELKULCS", 36,
					namespace = "eing"))
      addChildren(pointNode, newXMLNode("FRSZ_ID", currfid,
					namespace = "eing"))
      pointGeometry <- newXMLNode("geometry", parent=pointNode,
				  namespace = "eing")
      pointPoint <- newXMLNode("Point", parent=pointGeometry,
			       namespace = "gml")
      addAttributes(pointPoint, srsDimension = 2, srsName = srsName)
      addChildren(pointPoint,
		  newXMLNode("pos",
			     paste(addresscoordpoint, collapse = " "),
			     namespace = "gml"))
      ## Initial point id
      pontszam <- 52421
      ## Points assigned to the polygon
      for(actualpoints in 1:nrow(coords.matrix)) {
	  currfidother <- currfid + sample(1:5, 1)
	  actualpoint <- coords.matrix[actualpoints,]
	  pointNode <- newXMLNode("RESZLETPONTOK", parent=metadataNode,
				  namespace = "eing")
	  addAttributes(pointNode, "gml:id" = paste0("fid-", currfidother))
	  pointBounded <- newXMLNode("boundedBy", parent=pointNode,
				     namespace = "gml")
	  pointEnvelope <- newXMLNode("Envelope", parent=pointBounded,
				      namespace = "gml")
	  addAttributes(pointEnvelope, srsDimension = 2, srsName = srsName)
	  addChildren(pointEnvelope,
		      newXMLNode("lowerCorner",
				 paste(actualpoint, collapse = " "),
				 namespace = "gml"))
	  addChildren(pointEnvelope,
		      newXMLNode("upperCorner",
				 paste(actualpoint, collapse = " "),
				 namespace = "gml"))
	  addChildren(pointNode, newXMLNode("GEOBJ_ID", currfidother,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("OBJ_FELS", "AC02",
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("RETEG_ID", 6,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("RETEG_NEV", "Részletpontok" ,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("TELEPULES_ID", 3400,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("HRSZ",
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("FELIRAT", pontszam,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("SZINT", 0,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("IRANY", 0,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("MAGASSAG", 0,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("PONTSZAM", pontszam,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("PONTKOD", 4236,
					    namespace = "eing"))
	  addChildren(pointNode, newXMLNode("JELKULCS", 0,
					    namespace = "eing"))
	  pointGeometry <- newXMLNode("geometry", parent=pointNode,
				      namespace = "eing")
	  pointPoint <- newXMLNode("Point", parent=pointGeometry,
				   namespace = "gml")
	  addAttributes(pointPoint, srsDimension = 2, srsName = srsName)
	  addChildren(pointPoint,
		      newXMLNode("pos", paste(actualpoint, collapse = " "),
				 namespace = "gml"))
	  pontszam <- pontszam + sample(1:5, 1)
      }
      ## Save gml
      saveXML(gmlwithmeta,
	      file,
	      prefix='<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n')
  }
#+end_src
#+LATEX: \normalsize


A melléklet kódjának működtetése

#+begin_src R
  tesztkoord <- c(165800.00, 350000.00, 165813.85, 349994.25,
		  165844.47, 350068.17, 165830.61, 350073.91,
		  165800.00, 350000.00)
  BuildNew(tesztkoord)
#+end_src
